title: Bocchi7's Homepage
page-top-title: Bocchi7
top-section-bg-text: 
home-subtitle: Jiaqing Wu&ensp;|&ensp;吴家庆
copyright-text: '&copy; Bocchi7 2023-2025. All Rights Reserved.'
site_name: "Jiaqing Wu"
site_description: "Undergraduate Student"
email: "wu-jq22@mails.tsinghua.edu.cn"