title: Bocchi7's Homepage
page-top-title: Bocchi7
top-section-bg-text: Be what you wanna be
home-subtitle: Bocchi7&ensp;|&ensp;Bocchi7
copyright-text: '&copy; Bocchi7 2023-2025. All Rights Reserved.'
site_name: "Jiaqing Wu"
site_description: "Undergraduate Student"
email: "wu-jq22@mails.tsinghua.edu.cn"